image : node:latest

stages:
    - install
    - package
    - deploy

cache:
  paths:
    - node_modules/

install:
    stage: install
    script:
        - npm install
        - npm install -g @angular/cli
        - ng build
    artifacts:
      paths:
        - node_modules/

package:
    stage: package
    script:
      - ./node_modules/.bin/ng build --prod
    artifacts:
      paths:
        - dist/

deploy:
  image: python:lastest
  stage: deploy
  before_script:
    - pip install awscli
  script:
    - aws s3 sync ./dist s3://unedosedevert/ --acl=public-read --delete


    
