/**
 * Swagger Maven Plugin Sample
 * This is a sample.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Role {
    id?: number;
    name?: Role.NameEnum;
}

// tslint:disable-next-line:no-namespace
export namespace Role {
    export type NameEnum = 'ROLE_USER' | 'ROLE_ADMIN';
    export const NameEnum = {
        USER: 'ROLE_USER' as NameEnum,
        ADMIN: 'ROLE_ADMIN' as NameEnum
    };
}
